### ISSUE TITLE
Browsing OPC on an PLC / Nodes aren't visible

### ISSUE THREAD

**Issue by jfrsolutions** [onewayautomation/ogamma-logger#10] opened 2020-01-16 09:33 UTC
Hello,
i am installed the ogamma-logger with docker and it is working with the Demoserver
as an next step i try to discover the values on an PLC with an activated OPC-Server on it.
I can access to the Server and browser through the structure but i cant see any Nodes that i can add to observe. Insted of Nodes i get an "Icon" node

![PLC_Icon](https://user-images.githubusercontent.com/59956399/72511429-741d4780-384b-11ea-9d75-65b3a4972c6f.PNG)

If i use an other OPC Client is see all the values/nodes
Schuould i pay attention to some specific OPC Serversettings ?

**Comment by RavilN** [comment] 2020-01-16 15:46
Hello,
Please zip and send all files from folder "data" to support @ onewayautomation.com, I will investigate.
Also if you expand DataBlocksGlobal node in other UA client to see address space structure and send screenshot, will be helpful too.
Thank you for reporting this issue, Ravil

**Comment by RavilN** [comment] 2020-02-28 05:16
the issue was caused by the server returning only one reference in Browse response, with not null Continuation Point, which assumes that client should call BrowseNext requests in order to receive the rest of references.
Fixed in version 0.8.1 - now Visual Logger handles this case properly, calling BrowseNext.

**Closed as completed by RavilN** 2020-02-28 05:16 UTC
